const std = @import("std");

pub const SandboxResult = struct {
    success: bool,
    stdout: []const u8,
    stderr: []const u8,
    exit_code: u8,
};

pub const Sandbox = struct {
    allocator: std.mem.Allocator,
    tmp_dir_path: []const u8,

    pub fn init(allocator: std.mem.Allocator) !Sandbox {
        // Create a unique temporary directory for this sandbox session
        const rand_val = std.crypto.random.int(u64);
        const tmp_path = try std.fmt.allocPrint(allocator, "/tmp/ghost_sandbox_{x}", .{rand_val});
        
        std.fs.cwd().makeDir(tmp_path) catch |err| switch(err) {
            error.PathAlreadyExists => {},
            else => return err,
        };

        return .{
            .allocator = allocator,
            .tmp_dir_path = tmp_path,
        };
    }

    pub fn deinit(self: *Sandbox) void {
        std.fs.cwd().deleteTree(self.tmp_dir_path) catch {};
        self.allocator.free(self.tmp_dir_path);
    }

    pub fn verifyCode(self: *Sandbox, zig_code: []const u8) !SandboxResult {
        // Write the code to a file in the temp directory
        const main_path = try std.fmt.allocPrint(self.allocator, "{s}/main.zig", .{self.tmp_dir_path});
        defer self.allocator.free(main_path);

        const file = try std.fs.cwd().createFile(main_path, .{});
        try file.writeAll(zig_code);
        
        const harness = 
            \\
            \\// THE CONSTRAINT HARNESS (Generated by the Oracle)
            \\pub fn main() !void {
            \\    // Force the signature check
            \\    const result: [3]u8 = generated(42, 17);
            \\    _ = result;
            \\}
            \\
        ;
        try file.writeAll(harness);
        
        file.close();

        // Run zig build-exe (we use 'zig run' for immediate testing and output capture)
        var child = std.process.Child.init(&[_][]const u8{ "zig", "run", main_path }, self.allocator);
        child.stdout_behavior = .Pipe;
        child.stderr_behavior = .Pipe;
        
        // Timeout mechanism could be added here in a production system.
        try child.spawn();
        
        const stdout_bytes = try child.stdout.?.readToEndAlloc(self.allocator, 1024 * 1024);
        const stderr_bytes = try child.stderr.?.readToEndAlloc(self.allocator, 1024 * 1024);
        
        const term = try child.wait();
        
        const exit_code: u8 = switch (term) {
            .Exited => |code| code,
            else => 255, // 255 for crash/signal
        };

        return SandboxResult{
            .success = (exit_code == 0),
            .stdout = stdout_bytes,
            .stderr = stderr_bytes,
            .exit_code = exit_code,
        };
    }
};

test "Sandbox correctly identifies passing and failing code" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    var sandbox = try Sandbox.init(arena.allocator());
    defer sandbox.deinit();

    const passing_code = 
        \\const std = @import("std");
        \\pub fn main() !void {
        \\    std.debug.print("Hello Verified World!\n", .{});
        \\}
    ;

    const pass_res = try sandbox.verifyCode(passing_code);
    try std.testing.expect(pass_res.success == true);
    try std.testing.expect(pass_res.exit_code == 0);
    try std.testing.expect(std.mem.indexOf(u8, pass_res.stderr, "Hello Verified World!") != null);

    const failing_code = 
        \\const std = @import("std");
        \\pub fn main() !void {
        \\    this_variable_does_not_exist = 10;
        \\}
    ;

    const fail_res = try sandbox.verifyCode(failing_code);
    try std.testing.expect(fail_res.success == false);
    try std.testing.expect(fail_res.exit_code != 0);
    try std.testing.expect(std.mem.indexOf(u8, fail_res.stderr, "use of undeclared identifier") != null);
}
