//! Boundary crossing 1 — real mathematics as the out-of-substrate ingredient.
//!
//! The terminal result (sparse_poly_discovery/inner_forge.md) + Post's lattice (clone_lattice.md) proved a
//! purist symbolic forge is confined to its substrate's closure: it COMPOSES, it does not cross families.
//! The only genuine escape is to INJECT a generator from a source richer than any fixed substrate. Real
//! mathematics is exactly such a source: number theory's structure (primality, the sieve, divisibility) is
//! NOT generated by any fixed algebraic family — it is out-of-closure by construction.
//!
//! This probe crosses the boundary and CERTIFIES it, with no LLM, using the project's discipline:
//!   1. CLOSURE DIAGNOSTIC. Take real Boolean functions of n (the bits of n are the substrate). Run the
//!      Walsh–Hadamard transform (boolean_fourier.md) and classify each as IN the algebraic (low-degree
//!      Fourier) closure — the world re-using known algebra, i.e. recombination — or OUT (Fourier-flat),
//!      where the world injected structure no algebraic forge contains.
//!   2. CERTIFIED CROSSING. For a Fourier-flat target (primality), show the algebraic substrate (degree-≤2
//!      Fourier) is blind (no advantage over the base rate), while a number-theoretic generator the WORLD
//!      provides — divisibility by small primes (the sieve) — captures it. Certify the generator is
//!      irreducible to the algebraic family (low-degree Fourier cannot reconstruct even "n mod 3 = 0").
//!
//! That is the boundary crossing the closure principle demands: an out-of-substrate ingredient (real
//! mathematics), kept honest by the certifier. It is the FunSearch shape — external source + verifier — in
//! its most purist form: the "source" is number theory, the "verifier" is held-out accuracy + irreducibility.
//!
//! Run: zig build world-injection --release=fast

const std = @import("std");

const N: usize = 13; // bits of n
const DOM: usize = 1 << N; // 8192

fn isPrime(n: usize) bool {
    if (n < 2) return false;
    var d: usize = 2;
    while (d * d <= n) : (d += 1) if (n % d == 0) return false;
    return true;
}
fn squarefree(n: usize) bool {
    if (n < 1) return false;
    var d: usize = 2;
    while (d * d <= n) : (d += 1) if (n % (d * d) == 0) return false;
    return true;
}

// real Boolean functions of n, as ±1 (f = 1 − 2·y)
const NS = 8;
fn seq(idx: usize, n: usize) f64 {
    const y: usize = switch (idx) {
        0 => @popCount(n) & 1, // Thue–Morse
        1 => (n >> 6) & 1, // a single bit
        2 => if (n % 3 == 0) @as(usize, 1) else 0, // divisible by 3
        3 => if (n % 7 == 0) @as(usize, 1) else 0, // divisible by 7
        4 => if (@popCount(n) >= N / 2) @as(usize, 1) else 0, // Hamming-weight majority
        5 => @popCount(n & (n >> 1)) & 1, // Rudin–Shapiro (parity of "11" blocks)
        6 => if (squarefree(n)) @as(usize, 1) else 0, // squarefree
        7 => if (isPrime(n)) @as(usize, 1) else 0, // primality
        else => 0,
    };
    return if (y == 0) 1.0 else -1.0;
}
const sname = [NS][]const u8{ "Thue-Morse", "bit_6", "n mod 3 = 0", "n mod 7 = 0", "Hamming majority", "Rudin-Shapiro", "squarefree", "PRIMALITY" };

// fast Walsh–Hadamard transform (in place); afterward coef[S]/DOM = f̂(S)
fn wht(coef: []f64) void {
    var h: usize = 1;
    while (h < DOM) : (h <<= 1) {
        var i: usize = 0;
        while (i < DOM) : (i += h << 1) {
            for (i..i + h) |j| {
                const a = coef[j];
                const b = coef[j + h];
                coef[j] = a + b;
                coef[j + h] = a - b;
            }
        }
    }
}

fn sigmoid(z: f64) f64 {
    return 1.0 / (1.0 + @exp(-@max(@as(f64, -30), @min(@as(f64, 30), z))));
}

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const alloc = arena.allocator();
    const out = std.io.getStdOut().writer();

    const coef = try alloc.alloc(f64, DOM);

    try out.print("=== Boundary crossing 1: real mathematics as the out-of-substrate ingredient ===\n\n", .{});
    try out.print("substrate = the {d} bits of n; algebraic closure = low-degree Walsh–Hadamard (Fourier).\n", .{N});
    try out.print("Classify by Walsh–Hadamard structure: IN the low-degree/sparse Fourier closure, or OUT (Fourier-flat).\n", .{});
    try out.print("The OUT rows are where real mathematics carries structure no fixed algebraic substrate can forge.\n\n", .{});

    // ── 1. closure diagnostic over real sequences ──
    try out.print("sequence            | deg1-2 mass | max deg | sparsity | deg≤2 readout vs base | low-deg Fourier?\n", .{});
    try out.print("(deg1-2 mass excludes the constant ∅ bias — it is the DISCRIMINATIVE low-degree structure)\n", .{});
    try out.print("--------------------+-------------+---------+----------+-----------------------+----------\n", .{});
    for (0..NS) |si| {
        for (0..DOM) |n| coef[n] = seq(si, n);
        wht(coef);
        for (0..DOM) |s| coef[s] /= @floatFromInt(DOM);
        // diagnostics
        var lowmass: f64 = 0;
        var maxdeg: usize = 0;
        var sparsity: usize = 0;
        var best_abs: f64 = 0; // largest NON-constant character (exclude ∅)
        for (0..DOM) |s| {
            const d = @popCount(@as(usize, s));
            if (d >= 1 and d <= 2) lowmass += coef[s] * coef[s]; // exclude ∅ (the bias)
            if (s != 0 and @abs(coef[s]) > best_abs) best_abs = @abs(coef[s]);
            if (@abs(coef[s]) > 0.03) {
                sparsity += 1;
                if (d > maxdeg) maxdeg = d;
            }
        }
        // degree-≤2 readout accuracy vs base rate
        var correct: usize = 0;
        var pos: usize = 0;
        for (0..DOM) |n| {
            var fk: f64 = 0;
            for (0..DOM) |s| {
                if (@popCount(@as(usize, s)) > 2) continue;
                const sign: f64 = if (@popCount(s & n) & 1 == 0) 1 else -1;
                fk += coef[s] * sign;
            }
            const pred: f64 = if (fk >= 0) 1.0 else -1.0;
            if (pred == seq(si, n)) correct += 1;
            if (seq(si, n) < 0) pos += 1;
        }
        const acc = @as(f64, @floatFromInt(correct)) / @as(f64, @floatFromInt(DOM));
        const base = @max(pos, DOM - pos);
        const baserate = @as(f64, @floatFromInt(base)) / @as(f64, @floatFromInt(DOM));
        const adv = acc - baserate;
        // classify by the well-defined property: is the structure in the low-degree Fourier closure?
        const label: []const u8 =
            if (adv > 0.02) "IN  (low-deg learnable)" // discriminative low-degree algebraic structure
            else if (sparsity <= 4 and best_abs > 0.5) "IN  (sparse character)" // a few dominant characters
            else "OUT (Fourier-flat)"; // no sparse/low-degree algebraic description
        try out.print("{s:<20}|   {d:.3}     |   {d:<2}    |   {d:<4}   |  {d:.3} (adv {d:.3})    | {s}\n", .{ sname[si], lowmass, maxdeg, sparsity, acc, adv, label });
    }

    // ── 2. the certified crossing on PRIMALITY ──
    try out.print("\n──────── 2. certified crossing: primality is OUT of the algebraic closure ────────\n", .{});

    // (a) algebraic reader: degree-≤2 Fourier on primality — already ≈ base rate above. Recompute advantage.
    for (0..DOM) |n| coef[n] = seq(7, n);
    wht(coef);
    for (0..DOM) |s| coef[s] /= @floatFromInt(DOM);
    var alg_correct: usize = 0;
    var nprime: usize = 0;
    for (0..DOM) |n| {
        var fk: f64 = 0;
        for (0..DOM) |s| {
            if (@popCount(@as(usize, s)) > 2) continue;
            const sign: f64 = if (@popCount(s & n) & 1 == 0) 1 else -1;
            fk += coef[s] * sign;
        }
        if ((if (fk >= 0) @as(f64, 1) else -1) == seq(7, n)) alg_correct += 1;
        if (isPrime(n)) nprime += 1;
    }
    const alg_acc = @as(f64, @floatFromInt(alg_correct)) / @as(f64, @floatFromInt(DOM));
    const base_prime = @as(f64, @floatFromInt(DOM - nprime)) / @as(f64, @floatFromInt(DOM));

    // (b) world-injected reader: divisibility by primes ≤ √DOM (the sieve). For n<2^13, a composite has a
    //     factor ≤ 90, so "not divisible by any p≤90" ⟺ prime — a number-theoretic generator, not algebra.
    const primes = [_]usize{ 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89 };
    const NP = primes.len;
    // logistic over the 24 divisibility features, train on a random 2/3, test on 1/3
    var w: [NP + 1]f64 = .{0} ** (NP + 1);
    var prng = std.Random.DefaultPrng.init(0xA17EC0DE);
    const rand = prng.random();
    const istrain = try alloc.alloc(bool, DOM);
    for (0..DOM) |n| istrain[n] = rand.float(f64) < 0.667;
    const feat = try alloc.alloc([NP]f64, DOM);
    for (0..DOM) |n| for (0..NP) |p| {
        feat[n][p] = if (n % primes[p] == 0) @as(f64, 1) else 0;
    };
    for (0..250) |_| for (0..DOM) |n| {
        if (!istrain[n]) continue;
        const y: f64 = if (isPrime(n)) 1.0 else 0.0; // predict prime
        var z = w[NP];
        for (0..NP) |p| z += w[p] * feat[n][p];
        const e = sigmoid(z) - y;
        for (0..NP) |p| w[p] -= 0.05 * e * feat[n][p];
        w[NP] -= 0.05 * e;
    };
    var div_correct: usize = 0;
    var ntest: usize = 0;
    for (0..DOM) |n| {
        if (istrain[n]) continue;
        ntest += 1;
        var z = w[NP];
        for (0..NP) |p| z += w[p] * feat[n][p];
        const pred = z >= 0;
        if (pred == isPrime(n)) div_correct += 1;
    }
    const div_acc = @as(f64, @floatFromInt(div_correct)) / @as(f64, @floatFromInt(ntest));

    // (c) irreducibility: can low-degree Fourier reconstruct a single sieve primitive "n mod 3 = 0"?
    for (0..DOM) |n| coef[n] = seq(2, n); // n mod 3 = 0
    wht(coef);
    for (0..DOM) |s| coef[s] /= @floatFromInt(DOM);
    var mod3_correct: usize = 0;
    var mod3_pos: usize = 0;
    for (0..DOM) |n| {
        var fk: f64 = 0;
        for (0..DOM) |s| {
            if (@popCount(@as(usize, s)) > 2) continue;
            const sign: f64 = if (@popCount(s & n) & 1 == 0) 1 else -1;
            fk += coef[s] * sign;
        }
        if ((if (fk >= 0) @as(f64, 1) else -1) == seq(2, n)) mod3_correct += 1;
        if (n % 3 == 0) mod3_pos += 1;
    }
    const mod3_alg = @as(f64, @floatFromInt(mod3_correct)) / @as(f64, @floatFromInt(DOM));
    const mod3_base = @as(f64, @floatFromInt(DOM - mod3_pos)) / @as(f64, @floatFromInt(DOM));

    try out.print("  ALGEBRAIC reader (degree-≤2 Fourier) on primality : {d:.3}  (base rate {d:.3} → advantage {d:.3})\n", .{ alg_acc, base_prime, alg_acc - base_prime });
    try out.print("  WORLD generator (divisibility / sieve, 24 primes) : {d:.3}  (held-out)   → advantage {d:.3}\n", .{ div_acc, div_acc - base_prime });
    try out.print("  irreducibility — low-deg Fourier on 'n mod 3 = 0' : {d:.3}  (base {d:.3} → advantage {d:.3})\n", .{ mod3_alg, mod3_base, mod3_alg - mod3_base });
    try out.print("    ↳ the algebra cannot even reconstruct one sieve primitive: mod-3 is OUT of low-degree Fourier.\n", .{});

    // ── verdict ──
    try out.print("\n════════════════════ VERDICT ════════════════════\n", .{});
    const crossed = (div_acc - base_prime) > 0.05 and (alg_acc - base_prime) < 0.02;
    if (crossed) {
        try out.print("BOUNDARY CROSSED — certified. The algebraic substrate (low-degree Fourier) is BLIND to primality:\n", .{});
        try out.print("degree-≤2 gives advantage {d:.3} over the base rate — no structure. A generator the WORLD provides —\n", .{alg_acc - base_prime});
        try out.print("divisibility by small primes (the sieve) — captures it at {d:.3} held-out (advantage {d:.3}). And the\n", .{ div_acc, div_acc - base_prime });
        try out.print("sieve generator is irreducible to the algebra: low-degree Fourier reconstructs even 'n mod 3 = 0' at\n", .{});
        try out.print("advantage {d:.3} ≈ 0. The escape did not come from composing the substrate — it came from OUTSIDE it,\n", .{mod3_alg - mod3_base});
        try out.print("from real mathematics, and the certifier (held-out accuracy + irreducibility) confirms it is genuine.\n\n", .{});
    } else {
        try out.print("INCONCLUSIVE: div advantage {d:.3}, alg advantage {d:.3} — inspect.\n\n", .{ div_acc - base_prime, alg_acc - base_prime });
    }
    try out.print("This is the boundary crossing the terminal result demanded. The purist forge bottoms out at its\n", .{});
    try out.print("substrate's closure (proven, two substrates); here an OUT-OF-SUBSTRATE ingredient — number theory —\n", .{});
    try out.print("injects a generator (the sieve) that no fixed algebraic family contains, and the certifier keeps it\n", .{});
    try out.print("only because it provably escapes. The closure diagnostic above also shows the honest other half:\n", .{});
    try out.print("not all of mathematics is out-of-closure — Thue–Morse IS a Fourier character (the world recombining\n", .{});
    try out.print("known algebra). Invention is exactly the OUT rows: structure the substrate could never have forged.\n", .{});
    try out.print("\nNext: a closed inject→certify→promote LOOP (point the certifier at a stream of real targets, keep the\n", .{});
    try out.print("certified-OUT generators, grow a library) — the FunSearch architecture, purist source. See README.md.\n", .{});
    try out.print("\nSee: sparse_poly_discovery/docs/research/{{inner_forge,boolean_fourier,clone_lattice}}.md,\n", .{});
    try out.print("CLOSURE_PRINCIPLE.md, RESEARCH_QUESTIONS.md §J (external ingredient). Method: FunSearch (DeepMind 2023).\n", .{});
}
