const std = @import("std");
const flame = @import("flame");
const vsa = @import("vsa");
const void_eng = @import("void");

// Generated by engine_genesis.zig from outside-envelope chamber geometry.
// Local deterministic engine. No model call, no service call.

const FpWords = flame.ChamberCount / 64;
const Fingerprint = [FpWords]u64;
const GenomeNameHash: u64 = 0x9BBCD5731B3CB1EA;
const GenomeSeed: u64 = 0xD3DB779DA6DD8E30;
const RepairPasses: usize = 45;
const LockPeriod: usize = 2;
const CurlStride: usize = 29;
const CurlSpan: usize = 21;
const NoveltyPressure: i128 = 1024;
const CurlAmplitude: i128 = 64;

const AlienPrototype = Fingerprint{
    0x4B7A37C9F92B99F2,
    0x3961A37302DE0890,
    0xC4EB492A01BCF34F,
    0x264DC82DA48D8DE1,
    0xB1075EF0F9B2A400,
    0xBA101CDFDC4C4035,
    0xF7B928AF4066565A,
    0x2B10884F61377845,
};

const Metrics = struct {
    closure: u128,
    min_dist: u32,
    nearest: []const u8,
    mean_dist: f64,
    max_dist: u32,
};

fn bitAt(fp: Fingerprint, idx: usize) bool {
    return ((fp[idx / 64] >> @intCast(idx % 64)) & 1) != 0;
}

fn setBit(fp: *Fingerprint, idx: usize, value: bool) void {
    const mask = @as(u64, 1) << @intCast(idx % 64);
    if (value) fp[idx / 64] |= mask else fp[idx / 64] &= ~mask;
}

fn hammingFp(a: Fingerprint, b: Fingerprint) u32 {
    var d: u32 = 0;
    for (a, b) |aw, bw| d += @popCount(aw ^ bw);
    return d;
}

fn conceptFingerprint(c: vsa.Concept) Fingerprint {
    const hv = vsa.getConceptHV(c);
    var fp: Fingerprint = undefined;
    for (&fp, 0..) |*w, i| w.* = hv.data[i];
    return fp;
}

fn absI128(v: i128) i128 {
    return if (v < 0) -v else v;
}

fn chamberSign(chamber: [flame.ChamberCount]i128, idx: usize) bool {
    return chamber[idx] > 0;
}

fn setChamberSign(chamber: *[flame.ChamberCount]i128, idx: usize, want_positive: bool, min_magnitude: i128, rng: *u64) void {
    rng.* = void_eng.splitMix64(rng.*);
    var mag = absI128(chamber[idx]);
    const jitter = @as(i128, @intCast(rng.* % 4096));
    if (mag < min_magnitude) mag = min_magnitude + jitter;
    chamber[idx] = if (want_positive) mag else -mag;
}

fn chamberFromPrototype(seed: u64) [flame.ChamberCount]i128 {
    var out: [flame.ChamberCount]i128 = undefined;
    var s = seed ^ GenomeSeed;
    for (&out, 0..) |*slot, idx| {
        s = void_eng.splitMix64(s);
        const mag = NoveltyPressure + 24_000 + @as(i128, @intCast(s % 8192));
        slot.* = if (bitAt(AlienPrototype, idx)) mag else -mag;
    }
    return out;
}

fn enforcePrototype(state: *flame.FlameState, rng: *u64) void {
    for (0..flame.ChamberCount) |idx| {
        if (chamberSign(state.chamber, idx) != bitAt(AlienPrototype, idx)) {
            setChamberSign(&state.chamber, idx, bitAt(AlienPrototype, idx), NoveltyPressure, rng);
        }
    }
}

fn curlMagnitudes(state: *flame.FlameState, pass: usize, rng: *u64) void {
    var cursor = (pass * CurlStride) % flame.ChamberCount;
    var touched: usize = 0;
    while (touched < flame.ChamberCount / CurlSpan) : (touched += 1) {
        rng.* = void_eng.splitMix64(rng.* ^ @as(u64, @intCast(cursor)) ^ @as(u64, @intCast(pass)));
        const delta = @as(i128, @intCast(rng.* % @as(u64, @intCast(CurlAmplitude))));
        const sign: i128 = if (state.chamber[cursor] >= 0) 1 else -1;
        state.chamber[cursor] += sign * delta;
        cursor = (cursor + CurlStride) % flame.ChamberCount;
    }
}

fn repair(state: *flame.FlameState, passes: usize) void {
    var rng = GenomeSeed ^ state.kernel ^ GenomeNameHash;
    for (0..passes) |pass| {
        curlMagnitudes(state, pass, &rng);
        for (flame.Laws) |law| {
            const got = law.ca * state.chamber[law.a] + law.cb * state.chamber[law.b];
            const err = law.t - got;
            if (err == 0) continue;
            const denom = law.ca * law.ca + law.cb * law.cb;
            if (denom == 0) continue;
            const damp = @as(i128, @intCast(1 + (pass / LockPeriod)));
            const da = @divTrunc(err * law.ca, denom * damp);
            const db = @divTrunc(err * law.cb, denom * damp);
            state.chamber[law.a] += @max(-1_000_000_000_000, @min(1_000_000_000_000, da));
            state.chamber[law.b] += @max(-1_000_000_000_000, @min(1_000_000_000_000, db));
        }
        enforcePrototype(state, &rng);
    }
    state.closure_error = flame.closureError(state);
}

fn chamberFingerprint(chamber: [flame.ChamberCount]i128) Fingerprint {
    var fp: Fingerprint = [_]u64{0} ** FpWords;
    for (chamber, 0..) |v, i| if (v > 0) setBit(&fp, i, true);
    return fp;
}

fn measure(fp: Fingerprint, closure: u128, concept_fps: []const Fingerprint, names: []const []const u8) Metrics {
    var best: u32 = std.math.maxInt(u32);
    var best_name: []const u8 = "?";
    var max_d: u32 = 0;
    var sum: u64 = 0;
    for (concept_fps, names) |cfp, name| {
        const d = hammingFp(fp, cfp);
        sum += d;
        if (d > max_d) max_d = d;
        if (d < best) {
            best = d;
            best_name = name;
        }
    }
    return .{
        .closure = closure,
        .min_dist = best,
        .nearest = best_name,
        .mean_dist = @as(f64, @floatFromInt(sum)) / @as(f64, @floatFromInt(concept_fps.len)),
        .max_dist = max_d,
    };
}

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const aa = arena.allocator();
    var args = try std.process.argsWithAllocator(aa);
    defer args.deinit();
    _ = args.next();
    var trials: usize = 16;
    var passes: usize = RepairPasses;
    var csv_path: []const u8 = "results/generated_geometry_invention.csv";
    var base_seed: u64 = GenomeSeed;
    while (args.next()) |arg| {
        if (std.mem.startsWith(u8, arg, "--trials=")) trials = try std.fmt.parseInt(usize, arg["--trials=".len..], 10) else if (std.mem.startsWith(u8, arg, "--passes=")) passes = try std.fmt.parseInt(usize, arg["--passes=".len..], 10) else if (std.mem.startsWith(u8, arg, "--seed=")) base_seed = try std.fmt.parseInt(u64, arg["--seed=".len..], 16) else if (std.mem.startsWith(u8, arg, "--csv=")) csv_path = arg["--csv=".len..];
    }

    const fields = std.meta.fields(vsa.Concept);
    var concept_fps = try aa.alloc(Fingerprint, fields.len);
    var names = try aa.alloc([]const u8, fields.len);
    inline for (fields, 0..) |field, i| {
        concept_fps[i] = conceptFingerprint(@as(vsa.Concept, @enumFromInt(field.value)));
        names[i] = field.name;
    }
    var max_inter: u32 = 0;
    for (concept_fps, 0..) |a, i| for (i + 1..concept_fps.len) |j| {
        const d = hammingFp(a, concept_fps[j]);
        if (d > max_inter) max_inter = d;
    };

    if (std.fs.path.dirname(csv_path)) |dir| if (dir.len != 0) try std.fs.cwd().makePath(dir);
    var csv = try std.fs.cwd().createFile(csv_path, .{ .truncate = true });
    defer csv.close();
    try csv.writer().writeAll("trial,min_dist,nearest,closure,mean_dist,max_dist,past_envelope\n");

    const stdout = std.io.getStdOut().writer();
    try stdout.print("=== GENERATED GEOMETRY INVENTION ENGINE ===\n", .{});
    try stdout.print("genome=0x{X} passes={d} lock={d} stride={d} span={d} pressure={d} amplitude={d}\n", .{
        GenomeNameHash, passes, LockPeriod, CurlStride, CurlSpan, NoveltyPressure, CurlAmplitude,
    });
    try stdout.print("VSA max envelope={d}\n", .{max_inter});
    try stdout.writeAll("trial | min_dist | nearest          | closure      | mean  | max | past?\n");
    try stdout.writeAll("------|----------|------------------|--------------|-------|-----|------\n");

    var past: usize = 0;
    var best = Metrics{ .closure = std.math.maxInt(u128), .min_dist = 0, .nearest = "?", .mean_dist = 0, .max_dist = 0 };
    for (0..trials) |trial| {
        const seed = void_eng.splitMix64(base_seed +% @as(u64, @intCast(trial)) *% 0x9E3779B97F4A7C15);
        var state = flame.FlameState{
            .chamber = chamberFromPrototype(seed),
            .scar_bank = [_]u64{0} ** flame.ScarCount,
            .kernel = seed,
            .closure_error = 0,
        };
        state.closure_error = flame.closureError(&state);
        repair(&state, passes);
        const m = measure(chamberFingerprint(state.chamber), state.closure_error, concept_fps, names);
        const is_past = m.min_dist > max_inter;
        if (is_past) past += 1;
        if (m.min_dist > best.min_dist or (m.min_dist == best.min_dist and m.closure < best.closure)) best = m;
        try stdout.print("{d: >5} | {d: >8} | {s: <16} | {d: >12} | {d: >5.1} | {d: >3} | {s}\n", .{
            trial, m.min_dist, m.nearest, m.closure, m.mean_dist, m.max_dist, if (is_past) "YES" else "no",
        });
        try csv.writer().print("{d},{d},{s},{d},{d:.4},{d},{d}\n", .{
            trial, m.min_dist, m.nearest, m.closure, m.mean_dist, m.max_dist, @intFromBool(is_past),
        });
    }

    try stdout.print("\nVERDICT: past_envelope={d}/{d}; best_min={d}; best_closure={d}; csv={s}\n", .{
        past, trials, best.min_dist, best.closure, csv_path,
    });
}
