const std = @import("std");

// --- GEOMETRY ARTIFACT COMPILER ---
//
// Converts the generated outside-envelope geometry engine into a second-stage
// invention artifact: a readable design note plus a standalone Zig engine.
// This is still local and deterministic. It does not ask a model for a design.

const AlienPrototype = [_]u64{
    0x4B7A37C9F92B99F2,
    0x3961A37302DE0890,
    0xC4EB492A01BCF34F,
    0x264DC82DA48D8DE1,
    0xB1075EF0F9B2A400,
    0xBA101CDFDC4C4035,
    0xF7B928AF4066565A,
    0x2B10884F61377845,
};

const GenomeNameHash: u64 = 0x9BBCD5731B3CB1EA;
const GenomeSeed: u64 = 0xD3DB779DA6DD8E30;
const RepairPasses: usize = 45;
const LockPeriod: usize = 2;
const CurlStride: usize = 29;
const CurlSpan: usize = 21;
const NoveltyPressure: i128 = 1024;
const CurlAmplitude: i128 = 64;

fn splitMix64(x: u64) u64 {
    var z = x +% 0x9E3779B97F4A7C15;
    z = (z ^ (z >> 30)) *% 0xBF58476D1CE4E5B9;
    z = (z ^ (z >> 27)) *% 0x94D049BB133111EB;
    return z ^ (z >> 31);
}

fn prototypeHash() u64 {
    var h: u64 = GenomeNameHash ^ GenomeSeed;
    for (AlienPrototype, 0..) |word, idx| {
        h = splitMix64(h ^ word ^ @as(u64, @intCast(idx * 0x101)));
    }
    return h;
}

fn writeDesignDoc(path: []const u8, phase_count: usize, phase_stride: usize, braid_period: usize) !void {
    if (std.fs.path.dirname(path)) |dir| if (dir.len != 0) try std.fs.cwd().makePath(dir);
    var file = try std.fs.cwd().createFile(path, .{ .truncate = true });
    defer file.close();
    const w = file.writer();

    try w.print(
        \\# Phase Lattice Inventor
        \\
        \\Generated by `geometry_artifact_compiler.zig` from the outside-envelope geometry
        \\discovered by `generated_geometry_invention.zig`.
        \\
        \\This is the engine's requested next invention: a non-linguistic invention engine
        \\that does not start from English concepts. It works in phase-locked chamber
        \\geometry:
        \\
        \\1. Keep the outside-VSA prototype as the root language.
        \\2. Spawn several phase views of that geometry.
        \\3. Repair each phase against Flame laws without allowing collapse back into the
        \\   VSA concept envelope.
        \\4. Select the lowest-closure surviving phase.
        \\5. Treat the selected phase as the next invention substrate.
        \\
        \\This is not a proof of superhuman invention. It is a concrete local engine that
        \\thinks in geometry first and English only through this compiled artifact.
        \\
        \\## Generated Parameters
        \\
        \\- genome hash: `0x{X}`
        \\- phase count: `{d}`
        \\- phase stride: `{d}`
        \\- braid period: `{d}`
        \\- repair passes: `{d}`
        \\- lock period: `{d}`
        \\- curl stride: `{d}`
        \\- curl span: `{d}`
        \\- novelty pressure: `{d}`
        \\- curl amplitude: `{d}`
        \\
        \\## Run
        \\
        \\```sh
        \\./zig-out/bin/phase_lattice_inventor --trials=16 --csv=results/phase_lattice_inventor.csv
        \\```
        \\
        \\## What Would Count As Extraordinary
        \\
        \\The next bar is not better poetry. The next bar is a generated artifact that:
        \\
        \\- stays outside the VSA envelope,
        \\- beats the prior generated engine's `14829513` closure score,
        \\- emits a readable new algorithm or engine design,
        \\- then survives a holdout benchmark that was not used to generate it.
        \\
    , .{
        GenomeNameHash,
        phase_count,
        phase_stride,
        braid_period,
        RepairPasses,
        LockPeriod,
        CurlStride,
        CurlSpan,
        NoveltyPressure,
        CurlAmplitude,
    });
}

fn writeEngineSource(path: []const u8, phase_count: usize, phase_stride: usize, braid_period: usize) !void {
    if (std.fs.path.dirname(path)) |dir| if (dir.len != 0) try std.fs.cwd().makePath(dir);
    var file = try std.fs.cwd().createFile(path, .{ .truncate = true });
    defer file.close();
    const w = file.writer();

    try w.writeAll(
        \\const std = @import("std");
        \\const flame = @import("flame");
        \\const vsa = @import("vsa");
        \\const void_eng = @import("void");
        \\
        \\// Generated by geometry_artifact_compiler.zig.
        \\// Phase-lattice invention engine: geometry-native, local deterministic code.
        \\
        \\const FpWords = flame.ChamberCount / 64;
        \\const Fingerprint = [FpWords]u64;
        \\
    );
    try w.print("const GenomeNameHash: u64 = 0x{X};\n", .{GenomeNameHash});
    try w.print("const GenomeSeed: u64 = 0x{X};\n", .{GenomeSeed});
    try w.print("const RepairPasses: usize = {d};\n", .{RepairPasses});
    try w.print("const LockPeriod: usize = {d};\n", .{LockPeriod});
    try w.print("const CurlStride: usize = {d};\n", .{CurlStride});
    try w.print("const CurlSpan: usize = {d};\n", .{CurlSpan});
    try w.print("const NoveltyPressure: i128 = {d};\n", .{NoveltyPressure});
    try w.print("const CurlAmplitude: i128 = {d};\n", .{CurlAmplitude});
    try w.print("const PhaseCount: usize = {d};\n", .{phase_count});
    try w.print("const PhaseStride: usize = {d};\n", .{phase_stride});
    try w.print("const BraidPeriod: usize = {d};\n\n", .{braid_period});
    try w.writeAll("const AlienPrototype = Fingerprint{\n");
    for (AlienPrototype) |word| {
        try w.print("    0x{X:0>16},\n", .{word});
    }
    try w.writeAll(
        \\};
        \\
        \\const Metrics = struct {
        \\    closure: u128,
        \\    min_dist: u32,
        \\    nearest: []const u8,
        \\    mean_dist: f64,
        \\    max_dist: u32,
        \\    phase: usize,
        \\};
        \\
        \\fn bitAt(fp: Fingerprint, idx: usize) bool {
        \\    return ((fp[idx / 64] >> @intCast(idx % 64)) & 1) != 0;
        \\}
        \\
        \\fn setBit(fp: *Fingerprint, idx: usize, value: bool) void {
        \\    const mask = @as(u64, 1) << @intCast(idx % 64);
        \\    if (value) fp[idx / 64] |= mask else fp[idx / 64] &= ~mask;
        \\}
        \\
        \\fn hammingFp(a: Fingerprint, b: Fingerprint) u32 {
        \\    var d: u32 = 0;
        \\    for (a, b) |aw, bw| d += @popCount(aw ^ bw);
        \\    return d;
        \\}
        \\
        \\fn conceptFingerprint(c: vsa.Concept) Fingerprint {
        \\    const hv = vsa.getConceptHV(c);
        \\    var fp: Fingerprint = undefined;
        \\    for (&fp, 0..) |*w, i| w.* = hv.data[i];
        \\    return fp;
        \\}
        \\
        \\fn phaseFingerprint(phase: usize) Fingerprint {
        \\    if (phase == 0) return AlienPrototype;
        \\    var fp = AlienPrototype;
        \\    var h = void_eng.splitMix64(GenomeSeed ^ @as(u64, @intCast(phase)) ^ GenomeNameHash);
        \\    var step: usize = 0;
        \\    while (step < BraidPeriod) : (step += 1) {
        \\        h = void_eng.splitMix64(h ^ @as(u64, @intCast(step)));
        \\        const a = @as(usize, @intCast(h)) % flame.ChamberCount;
        \\        const b = (a + PhaseStride + phase * CurlStride) % flame.ChamberCount;
        \\        const av = bitAt(fp, a);
        \\        const bv = bitAt(fp, b);
        \\        setBit(&fp, a, bv);
        \\        setBit(&fp, b, av);
        \\    }
        \\    return fp;
        \\}
        \\
        \\fn absI128(v: i128) i128 {
        \\    return if (v < 0) -v else v;
        \\}
        \\
        \\fn chamberSign(chamber: [flame.ChamberCount]i128, idx: usize) bool {
        \\    return chamber[idx] > 0;
        \\}
        \\
        \\fn setChamberSign(chamber: *[flame.ChamberCount]i128, idx: usize, want_positive: bool, min_magnitude: i128, rng: *u64) void {
        \\    rng.* = void_eng.splitMix64(rng.*);
        \\    var mag = absI128(chamber[idx]);
        \\    const jitter = @as(i128, @intCast(rng.* % 4096));
        \\    if (mag < min_magnitude) mag = min_magnitude + jitter;
        \\    chamber[idx] = if (want_positive) mag else -mag;
        \\}
        \\
        \\fn chamberFromFingerprint(fp: Fingerprint, seed: u64, phase: usize) [flame.ChamberCount]i128 {
        \\    var out: [flame.ChamberCount]i128 = undefined;
        \\    var s = seed ^ GenomeSeed ^ @as(u64, @intCast(phase));
        \\    for (&out, 0..) |*slot, idx| {
        \\        s = void_eng.splitMix64(s);
        \\        const mag = NoveltyPressure + 24_000 + @as(i128, @intCast(s % 8192));
        \\        slot.* = if (bitAt(fp, idx)) mag else -mag;
        \\    }
        \\    return out;
        \\}
        \\
        \\fn enforceFingerprint(state: *flame.FlameState, fp: Fingerprint, rng: *u64) void {
        \\    for (0..flame.ChamberCount) |idx| {
        \\        if (chamberSign(state.chamber, idx) != bitAt(fp, idx)) {
        \\            setChamberSign(&state.chamber, idx, bitAt(fp, idx), NoveltyPressure, rng);
        \\        }
        \\    }
        \\}
        \\
        \\fn phaseBraid(state: *flame.FlameState, phase: usize, pass: usize, rng: *u64) void {
        \\    var cursor = (pass * CurlStride + phase * PhaseStride) % flame.ChamberCount;
        \\    var touched: usize = 0;
        \\    while (touched < flame.ChamberCount / CurlSpan) : (touched += 1) {
        \\        rng.* = void_eng.splitMix64(rng.* ^ @as(u64, @intCast(cursor)) ^ @as(u64, @intCast(pass + phase)));
        \\        const delta = @as(i128, @intCast(rng.* % @as(u64, @intCast(CurlAmplitude))));
        \\        const sign: i128 = if (state.chamber[cursor] >= 0) 1 else -1;
        \\        state.chamber[cursor] += sign * delta;
        \\        cursor = (cursor + CurlStride + phase + 1) % flame.ChamberCount;
        \\    }
        \\}
        \\
        \\fn repair(state: *flame.FlameState, fp: Fingerprint, phase: usize, passes: usize) void {
        \\    var rng = GenomeSeed ^ state.kernel ^ GenomeNameHash ^ @as(u64, @intCast(phase));
        \\    for (0..passes) |pass| {
        \\        phaseBraid(state, phase, pass, &rng);
        \\        for (flame.Laws) |law| {
        \\            const got = law.ca * state.chamber[law.a] + law.cb * state.chamber[law.b];
        \\            const err = law.t - got;
        \\            if (err == 0) continue;
        \\            const denom = law.ca * law.ca + law.cb * law.cb;
        \\            if (denom == 0) continue;
        \\            const damp = @as(i128, @intCast(1 + (pass / LockPeriod)));
        \\            const da = @divTrunc(err * law.ca, denom * damp);
        \\            const db = @divTrunc(err * law.cb, denom * damp);
        \\            state.chamber[law.a] += @max(-1_000_000_000_000, @min(1_000_000_000_000, da));
        \\            state.chamber[law.b] += @max(-1_000_000_000_000, @min(1_000_000_000_000, db));
        \\        }
        \\        enforceFingerprint(state, fp, &rng);
        \\    }
        \\    state.closure_error = flame.closureError(state);
        \\}
        \\
        \\fn chamberFingerprint(chamber: [flame.ChamberCount]i128) Fingerprint {
        \\    var fp: Fingerprint = [_]u64{0} ** FpWords;
        \\    for (chamber, 0..) |v, i| if (v > 0) setBit(&fp, i, true);
        \\    return fp;
        \\}
        \\
        \\fn measure(fp: Fingerprint, closure: u128, concept_fps: []const Fingerprint, names: []const []const u8, phase: usize) Metrics {
        \\    var best: u32 = std.math.maxInt(u32);
        \\    var best_name: []const u8 = "?";
        \\    var max_d: u32 = 0;
        \\    var sum: u64 = 0;
        \\    for (concept_fps, names) |cfp, name| {
        \\        const d = hammingFp(fp, cfp);
        \\        sum += d;
        \\        if (d > max_d) max_d = d;
        \\        if (d < best) {
        \\            best = d;
        \\            best_name = name;
        \\        }
        \\    }
        \\    return .{
        \\        .closure = closure,
        \\        .min_dist = best,
        \\        .nearest = best_name,
        \\        .mean_dist = @as(f64, @floatFromInt(sum)) / @as(f64, @floatFromInt(concept_fps.len)),
        \\        .max_dist = max_d,
        \\        .phase = phase,
        \\    };
        \\}
        \\
        \\fn better(a: Metrics, b: Metrics, max_inter: u32) bool {
        \\    const ap = a.min_dist > max_inter;
        \\    const bp = b.min_dist > max_inter;
        \\    if (ap != bp) return ap;
        \\    if (a.closure != b.closure) return a.closure < b.closure;
        \\    return a.min_dist > b.min_dist;
        \\}
        \\
        \\pub fn main() !void {
        \\    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
        \\    defer arena.deinit();
        \\    const aa = arena.allocator();
        \\    var args = try std.process.argsWithAllocator(aa);
        \\    defer args.deinit();
        \\    _ = args.next();
        \\    var trials: usize = 16;
        \\    var passes: usize = RepairPasses;
        \\    var csv_path: []const u8 = "results/phase_lattice_inventor.csv";
        \\    var base_seed: u64 = GenomeSeed;
        \\    while (args.next()) |arg| {
        \\        if (std.mem.startsWith(u8, arg, "--trials=")) trials = try std.fmt.parseInt(usize, arg["--trials=".len..], 10)
        \\        else if (std.mem.startsWith(u8, arg, "--passes=")) passes = try std.fmt.parseInt(usize, arg["--passes=".len..], 10)
        \\        else if (std.mem.startsWith(u8, arg, "--seed=")) base_seed = try std.fmt.parseInt(u64, arg["--seed=".len..], 16)
        \\        else if (std.mem.startsWith(u8, arg, "--csv=")) csv_path = arg["--csv=".len..];
        \\    }
        \\
        \\    const fields = std.meta.fields(vsa.Concept);
        \\    var concept_fps = try aa.alloc(Fingerprint, fields.len);
        \\    var names = try aa.alloc([]const u8, fields.len);
        \\    inline for (fields, 0..) |field, i| {
        \\        concept_fps[i] = conceptFingerprint(@as(vsa.Concept, @enumFromInt(field.value)));
        \\        names[i] = field.name;
        \\    }
        \\    var max_inter: u32 = 0;
        \\    for (concept_fps, 0..) |a, i| for (i + 1..concept_fps.len) |j| {
        \\        const d = hammingFp(a, concept_fps[j]);
        \\        if (d > max_inter) max_inter = d;
        \\    };
        \\
        \\    if (std.fs.path.dirname(csv_path)) |dir| if (dir.len != 0) try std.fs.cwd().makePath(dir);
        \\    var csv = try std.fs.cwd().createFile(csv_path, .{ .truncate = true });
        \\    defer csv.close();
        \\    try csv.writer().writeAll("trial,phase,min_dist,nearest,closure,mean_dist,max_dist,past_envelope\n");
        \\
        \\    const stdout = std.io.getStdOut().writer();
        \\    try stdout.print("=== PHASE LATTICE INVENTOR ===\n", .{});
        \\    try stdout.print("phases={d} passes={d} stride={d} braid={d} envelope={d}\n", .{ PhaseCount, passes, PhaseStride, BraidPeriod, max_inter });
        \\    try stdout.writeAll("trial | phase | min_dist | nearest          | closure      | mean  | max | past?\n");
        \\    try stdout.writeAll("------|-------|----------|------------------|--------------|-------|-----|------\n");
        \\
        \\    var past: usize = 0;
        \\    var global_best = Metrics{ .closure = std.math.maxInt(u128), .min_dist = 0, .nearest = "?", .mean_dist = 0, .max_dist = 0, .phase = 0 };
        \\    for (0..trials) |trial| {
        \\        const seed = void_eng.splitMix64(base_seed +% @as(u64, @intCast(trial)) *% 0xD1B54A32D192ED03);
        \\        var best = global_best;
        \\        best.closure = std.math.maxInt(u128);
        \\        for (0..PhaseCount) |phase| {
        \\            const fp = phaseFingerprint(phase);
        \\            var state = flame.FlameState{
        \\                .chamber = chamberFromFingerprint(fp, seed, phase),
        \\                .scar_bank = [_]u64{0} ** flame.ScarCount,
        \\                .kernel = seed ^ @as(u64, @intCast(phase)),
        \\                .closure_error = 0,
        \\            };
        \\            state.closure_error = flame.closureError(&state);
        \\            repair(&state, fp, phase, passes);
        \\            const m = measure(chamberFingerprint(state.chamber), state.closure_error, concept_fps, names, phase);
        \\            if (better(m, best, max_inter)) best = m;
        \\        }
        \\        const is_past = best.min_dist > max_inter;
        \\        if (is_past) past += 1;
        \\        if (better(best, global_best, max_inter)) global_best = best;
        \\        try stdout.print("{d: >5} | {d: >5} | {d: >8} | {s: <16} | {d: >12} | {d: >5.1} | {d: >3} | {s}\n", .{
        \\            trial, best.phase, best.min_dist, best.nearest, best.closure, best.mean_dist, best.max_dist, if (is_past) "YES" else "no",
        \\        });
        \\        try csv.writer().print("{d},{d},{d},{s},{d},{d:.4},{d},{d}\n", .{
        \\            trial, best.phase, best.min_dist, best.nearest, best.closure, best.mean_dist, best.max_dist, @intFromBool(is_past),
        \\        });
        \\    }
        \\
        \\    try stdout.print("\nVERDICT: phase_lattice_past_envelope={d}/{d}; best_phase={d}; best_min={d}; best_closure={d}; csv={s}\n", .{
        \\        past, trials, global_best.phase, global_best.min_dist, global_best.closure, csv_path,
        \\    });
        \\}
        \\
    );
}

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const aa = arena.allocator();

    var args = try std.process.argsWithAllocator(aa);
    defer args.deinit();
    _ = args.next();

    var source_path: []const u8 = "src/adapters/phase_lattice_inventor.zig";
    var doc_path: []const u8 = "docs/research/phase_lattice_inventor.md";
    while (args.next()) |arg| {
        if (std.mem.startsWith(u8, arg, "--source=")) source_path = arg["--source=".len..] else if (std.mem.startsWith(u8, arg, "--doc=")) doc_path = arg["--doc=".len..];
    }

    const h = prototypeHash();
    const phase_count = 5 + @as(usize, @intCast(h % 4));
    var phase_stride = 17 + @as(usize, @intCast((h >> 8) % 73));
    if (phase_stride % 2 == 0) phase_stride += 1;
    const braid_period = 64 + @as(usize, @intCast((h >> 16) % 193));

    try writeEngineSource(source_path, phase_count, phase_stride, braid_period);
    try writeDesignDoc(doc_path, phase_count, phase_stride, braid_period);

    const stdout = std.io.getStdOut().writer();
    try stdout.print("=== GEOMETRY ARTIFACT COMPILER ===\n", .{});
    try stdout.print("source={s}\ndoc={s}\n", .{ source_path, doc_path });
    try stdout.print("phase_count={d} phase_stride={d} braid_period={d} prototype_hash=0x{X}\n", .{
        phase_count,
        phase_stride,
        braid_period,
        h,
    });
}
