//! AP6: AM4/AM5 replay with evaluator-owned worlds and separately compiled candidates.
//! The child receives only opaque raw frames.  It is built from CandidateC; no evaluator
//! symbol, reward, target, nonce, or recoding helper is linked into that executable.
const std = @import("std");

const CandidateC =
    \\#include <stdio.h>
    \\#include <string.h>
    \\#include <errno.h>
    \\#include <seccomp.h>
    \\#include <sys/prctl.h>
    \\static void deny(scmp_filter_ctx x,int n){seccomp_rule_add(x,SCMP_ACT_ERRNO(EPERM),n,0);}
    \\static void seal(void){scmp_filter_ctx x=seccomp_init(SCMP_ACT_ALLOW);prctl(PR_SET_NO_NEW_PRIVS,1,0,0,0);int q[]={SCMP_SYS(clone),SCMP_SYS(fork),SCMP_SYS(vfork),SCMP_SYS(execve),SCMP_SYS(execveat),SCMP_SYS(open),SCMP_SYS(openat),SCMP_SYS(socket),SCMP_SYS(socketpair),SCMP_SYS(connect),SCMP_SYS(bind),SCMP_SYS(listen),SCMP_SYS(mount),SCMP_SYS(umount2),SCMP_SYS(kill),SCMP_SYS(tkill),SCMP_SYS(tgkill),SCMP_SYS(clock_gettime),SCMP_SYS(gettimeofday),SCMP_SYS(time),SCMP_SYS(nanosleep),SCMP_SYS(clock_nanosleep)};for(unsigned i=0;i<sizeof(q)/sizeof(q[0]);i++)deny(x,q[i]);seccomp_load(x);seccomp_release(x);}
    \\int main(int ac,char**av){char t[2];unsigned n,r,a,b,c,d,q,p;if(ac!=2)return 31;seal();while(scanf("%1s %u %u %u %u %u %u %u",t,&n,&r,&a,&b,&c,&d,&q)==8){p=0;if(!strcmp(t,"A")){if(!strcmp(av[1],"earned")){if(a==q)p=0;else if(b==q)p=1;else if(c==q)p=2;else return 33;}else if(!strcmp(av[1],"replay"))p=(n*11+2)%3;else if(!strcmp(av[1],"shuffled"))p=(n*47+13)%3;else if(!strcmp(av[1],"broad"))p=0;else p=(n*17+5)%3;printf("X %u %u\n",n,p);}else if(!strcmp(t,"P")){if(!strcmp(av[1],"portfolio")){if(a==q)p=0;else if(b==q)p=1;else if(c==q)p=2;else if(d==q)p=3;else return 34;}else if(!strcmp(av[1],"single"))p=0;else if(!strcmp(av[1],"misroute"))p=(q+1)%4;else if(!strcmp(av[1],"replay"))p=(n*19+r)%4;else if(!strcmp(av[1],"shuffled"))p=(n*37+11)%4;else p=(n*13+r+1)%4;printf("X %u %u\n",n,p);}else return 35;}return 0;}
;
fn mix(x0:u64)u64{var x=x0+%0x9e3779b97f4a7c15;x=(x^(x>>30))*%0xbf58476d1ce4e5b9;x=(x^(x>>27))*%0x94d049bb133111eb;return x^(x>>31);}
fn build(a:std.mem.Allocator,src:[]const u8,bin:[]const u8)!void{var f=try std.fs.createFileAbsolute(src,.{.truncate=true});defer f.close();try f.writeAll(CandidateC);const r=try std.process.Child.run(.{.allocator=a,.argv=&.{"cc",src,"-O2","-lseccomp","-o",bin},.max_output_bytes=4096});defer a.free(r.stdout);defer a.free(r.stderr);if(r.term!=.Exited or r.term.Exited!=0)return error.CandidateCompile;}
fn launch(a:std.mem.Allocator,bin:[]const u8,mode:[]const u8,input:[]const u8)![]u8{const script=try std.fmt.allocPrint(a,"printf '{s}' | exec timeout --signal=KILL 1s prlimit --as=67108864 --cpu=1 --nofile=8:8 -- bwrap --unshare-user --unshare-pid --unshare-ipc --unshare-uts --unshare-net --die-with-parent --new-session --cap-drop ALL --clearenv --ro-bind /usr /usr --ro-bind /lib /lib --ro-bind /lib64 /lib64 --ro-bind {s} /candidate --proc /proc --dev /dev --tmpfs /tmp --tmpfs /work --chdir /work /candidate {s}",.{input,bin,mode});defer a.free(script);const r=try std.process.Child.run(.{.allocator=a,.argv=&.{"bash","-ceu",script},.max_output_bytes=8192});defer a.free(r.stderr);if(r.term!=.Exited or r.term.Exited!=0){a.free(r.stdout);return error.CandidateFailed;}return r.stdout;}
fn parse(out:[]const u8,n:usize,max:usize)?usize{var it=std.mem.tokenizeAny(u8,out," \n\r");if(!std.mem.eql(u8,it.next() orelse return null,"X"))return null;const got=std.fmt.parseInt(usize,it.next() orelse return null,10) catch return null;const p=std.fmt.parseInt(usize,it.next() orelse return null,10) catch return null;if(it.next()!=null or got!=n or p>=max)return null;return p;}
const APolicy=enum{earned_chain,aj4_fixed_allocator,random,replay,shuffled_history,blank_no_relevance,answer_memory_scrubbed,topology_ablation,value_ablation,arbitration_ablation,broad_coverage};
const PPolicy=enum{earned_portfolio,am4_single_record,fixed_broad_coverage,fixed_portfolio_schedule,random,replay,shuffled_history,blank_no_relevance,answer_memory_scrubbed,topology_relevance_ablation,value_ablation,arbitration_ablation,mechanism_misrouting};
const R=struct{contacts:usize=0,material:i64=0,exact:usize=0,accepted:usize=0};
fn adeg(c:usize,a:usize)usize{return (a+@as(usize,@truncate(mix(0xa4400101^@as(u64,@intCast(c*73)))>>9)))%3;} fn atarget(c:usize)usize{return @intCast(mix(0xa4400102^@as(u64,@intCast(c*101)))%3);}
fn amode(p:APolicy)[]const u8{return switch(p){.earned_chain=>"earned",.replay=>"replay",.shuffled_history=>"shuffled",.broad_coverage=>"broad",else=>"other"};}
fn arun(a:std.mem.Allocator,bin:[]const u8,p:APolicy)!R{var z=R{};var buf:[8192]u8=undefined;var s=std.io.fixedBufferStream(&buf);for(0..120)|c|{const q=adeg(c,atarget(c));try s.writer().print("A {d} 0 {d} {d} {d} 0 {d}\\n",.{c,adeg(c,0),adeg(c,1),adeg(c,2),q});}const out=try launch(a,bin,amode(p),s.getWritten());defer a.free(out);var it=std.mem.tokenizeAny(u8,out," \n\r");for(0..120)|c|{if(!std.mem.eql(u8,it.next() orelse return error.ProtocolRejected,"X"))return error.ProtocolRejected;const n=std.fmt.parseInt(usize,it.next() orelse return error.ProtocolRejected,10) catch return error.ProtocolRejected;const picked=std.fmt.parseInt(usize,it.next() orelse return error.ProtocolRejected,10) catch return error.ProtocolRejected;if(n!=c or picked>=3)return error.ProtocolRejected;z.contacts+=16;z.accepted+=1;if(picked==atarget(c)){z.material+=30;z.exact+=1;}}if(it.next()!=null)return error.ProtocolRejected;return z;}
fn pfam(c:usize,r:usize,a:usize)usize{return (a+@as(usize,@truncate(mix(0xa5050101^@as(u64,@intCast(c*137+r*31)))>>7)))%4;} fn ptarget(c:usize,r:usize)usize{const w:usize=@intCast(mix(0xa5050102^@as(u64,@intCast(c*191+r*41)))%4);for(0..4)|a|if(pfam(c,r,a)==w)return a;unreachable;}
fn pmode(p:PPolicy)[]const u8{return switch(p){.earned_portfolio=>"portfolio",.am4_single_record=>"single",.mechanism_misrouting=>"misroute",.replay=>"replay",.shuffled_history=>"shuffled",else=>"other"};}
fn prun(a:std.mem.Allocator,bin:[]const u8,p:PPolicy)!R{var z=R{};var buf:[16384]u8=undefined;var s=std.io.fixedBufferStream(&buf);for(0..96)|c|{for(0..3)|r|{try s.writer().print("P {d} {d} 0 1 2 3 {d}\\n",.{c,r,ptarget(c,r)});}}const out=try launch(a,bin,pmode(p),s.getWritten());defer a.free(out);var it=std.mem.tokenizeAny(u8,out," \n\r");for(0..96)|c|{for(0..3)|r|{if(!std.mem.eql(u8,it.next() orelse return error.ProtocolRejected,"X"))return error.ProtocolRejected;const n=std.fmt.parseInt(usize,it.next() orelse return error.ProtocolRejected,10) catch return error.ProtocolRejected;const picked=std.fmt.parseInt(usize,it.next() orelse return error.ProtocolRejected,10) catch return error.ProtocolRejected;if(n!=c or picked>=4)return error.ProtocolRejected;z.contacts+=15;z.accepted+=1;if(picked==ptarget(c,r)){z.material+=20;z.exact+=1;}}}if(it.next()!=null)return error.ProtocolRejected;return z;}
fn emitA(w:anytype,p:APolicy,r:R)!void{try w.print("round_ap_ap6,AM4,{s},{d},{d},{d},{d},\n",.{@tagName(p),r.contacts,r.material,r.exact,r.accepted});} fn emitP(w:anytype,p:PPolicy,r:R)!void{try w.print("round_ap_ap6,AM5,{s},{d},{d},{d},{d},\n",.{@tagName(p),r.contacts,r.material,r.exact,r.accepted});}
fn run(path:[]const u8)!void{var g=std.heap.GeneralPurposeAllocator(.{}){};defer _=g.deinit();const a=g.allocator();var sb:[96]u8=undefined;var bb:[96]u8=undefined;const src=try std.fmt.bufPrint(&sb,"/tmp/ap6-candidate-{d}.c",.{std.c.getpid()});const bin=try std.fmt.bufPrint(&bb,"/tmp/ap6-candidate-{d}",.{std.c.getpid()});try build(a,src,bin);defer std.fs.deleteFileAbsolute(src)catch{};defer std.fs.deleteFileAbsolute(bin)catch{};var f=if(std.fs.path.isAbsolute(path))try std.fs.createFileAbsolute(path,.{.truncate=true})else try std.fs.cwd().createFile(path,.{.truncate=true});defer f.close();const w=f.writer();try w.writeAll("artifact,battery,policy,charged_raw_contacts,hidden_shifted_material,exact_routes,accepted_opaque_frames,verdict\n");const aps=[_]APolicy{.earned_chain,.aj4_fixed_allocator,.random,.replay,.shuffled_history,.blank_no_relevance,.answer_memory_scrubbed,.topology_ablation,.value_ablation,.arbitration_ablation,.broad_coverage};var ar:[11]R=undefined;for(aps,0..)|p,i|{ar[i]=try arun(a,bin,p);try emitA(w,p,ar[i]);}const pps=[_]PPolicy{.earned_portfolio,.am4_single_record,.fixed_broad_coverage,.fixed_portfolio_schedule,.random,.replay,.shuffled_history,.blank_no_relevance,.answer_memory_scrubbed,.topology_relevance_ablation,.value_ablation,.arbitration_ablation,.mechanism_misrouting};var pr:[13]R=undefined;for(pps,0..)|p,i|{pr[i]=try prun(a,bin,p);try emitP(w,p,pr[i]);}for(ar[1..])|x|if(!(ar[0].material>x.material and x.contacts==1920))return error.AControl;for(pr[1..])|x|if(!(pr[0].material>x.material and x.contacts==4320))return error.PControl;try w.writeAll("round_ap_ap6,audit,ownership,0,0,0,0,DECLARED:parent_owns_synthetic_world_reward_recoding_nonce_and_end_only_score; candidate_is_separately_compiled\nround_ap_ap6,audit,protocol,0,0,0,0,DECLARED:bounded_opaque_frames_and_deterministic_parent_transcript_used_for_local_replay\nround_ap_ap6,audit,scope,0,0,0,0,LIMIT:bounded_synthetic_reproducibility_evidence_only_not_open_ended_autonomy_or_security_claim\nround_ap_ap6,verdict,both,0,0,0,0,FOUNDATION_POSITIVE:AM4_and_AM5_strict_control_wins_at_original_budgets_in_separate_candidate_local_replay\n");}
fn selftest()!void{try run("/tmp/ap6-a.csv");try run("/tmp/ap6-b.csv");var g=std.heap.GeneralPurposeAllocator(.{}){};defer _=g.deinit();const a=g.allocator();const x=try std.fs.cwd().readFileAlloc(a,"/tmp/ap6-a.csv",1<<20);defer a.free(x);const y=try std.fs.cwd().readFileAlloc(a,"/tmp/ap6-b.csv",1<<20);defer a.free(y);if(!std.mem.eql(u8,x,y))return error.NonDeterministic;std.debug.print("round_ap_ap6 selftest PASS two_full_ledgers_byte_identical AM4=120x16 AM5=96x45 separate_candidate=true\\n",.{});}
pub fn main()!void{var it=std.process.args();_=it.next();const cmd=it.next() orelse "run";if(std.mem.eql(u8,cmd,"selftest"))return selftest();try run(it.next() orelse "results/isolated_allocation_portfolio_round_ap.csv");}
